### PR TITLE
Fix imageSmoothing property name

### PR DESCRIPTION
**Pull request by arkonisus**

### CODE REVIEW

**Comment by arkonisus** [comment]
Sry, i closed this PR by mistake ... :)

**Comment by caleb531** [comment]
@arkonisus I intentionally named this property `imageSmoothing` for the sake of brevity. Regardless, I cannot afford to change the name for the sake of maintaining API backwards-compatibility. Therfore, sorry to say, I do not intend to merge this PR.

**Comment by arkonisus** [comment]
Yes, the property-name "imageSmoothing" is correct. But your code doesn't work because you named it "imageSmoothingEnabled". Please give it a try:
`$(canvas).drawImage({
			  source: url,
			  imageSmoothing: true
			});`

**Comment by caleb531** [comment]
Oh, my apologies—I read your diff completely backwards. I will absolutely merge this in, then.

**Comment by caleb531** [comment]
@arkonisus BTW, I will try to publish a new release within the next few days.

**Comment by arkonisus** [comment]
@caleb531 Thank you very much!

**Comment by caleb531** [comment]
@arkonisus And... v20.1.3 (which incorporates this fix) has been pushed!

Enjoy,  
Caleb

**Pull request merged**
