### PR TITLE
Add AMD wrapper like jQuery does.

### PR DESCRIPTION
**Pull request by robertjustjones**
Hey, Caleb, I've added an AMD wrapper here inspired by jQuery's to allow jcanvas to be used in node.js. See what you think. I do have it working but with pending PR's on two other projects. Once those get in, I can add a how-to.

### CODE REVIEW

**Comment by caleb531** [comment]
Great, thanks very much, @robertjustjones. However, I would prefer to wait until you add the how-to before I merge this in. I also prefer that you add the global definitions (`window.document`, `window.Math`, etc.) on separate lines.

Caleb

**Comment by robertjustjones** [comment]
Caleb, here's the demo. It depends on PR's to work for now.
https://github.com/robertjustjones/jcanvas-in-node

 To install, you'll need to follow the Cairo [installation instructions for node-canvas]
(https://github.com/Automattic/node-canvas/wiki).

After cloning, do ```npm install``` and then ```node index.js```.

**Comment by caleb531** [comment]
Looks good to me. I'll merge this in now, and add your documentation to the README.

**Comment by robertjustjones** [comment]
Thanks, Caleb!

**Comment by caleb531** [comment]
Sure thing, @robertjustjones. :) However, as I needed to make a few tweaks before pushing a new release, I need your help in testing the new release, just to make sure everything works right. You can expect me to push it within the hour.

Caleb

**Comment by caleb531** [comment]
Changes pushed—please test when you can. :)

**Comment by robertjustjones** [comment]
15.2.7 confirmed! 

Now you'll have to think about putting it on npmjs ;-).

**Comment by caleb531** [comment]
jCanvas already has a `package.json` file. Is that not enough?

**Comment by robertjustjones** [comment]
That works, but to simplify ```npm install``` you'll want to put it here. https://www.npmjs.com/search?q=jcanvas

**Comment by caleb531** [comment]
Great, thanks—I'll consider it. :)

Caleb

**Comment by robertjustjones** [comment]
Here's [jQuery](https://www.npmjs.com/package/jquery).  At any rate, grab the jcanvas name now.

**Comment by caleb531** [comment]
Done! https://www.npmjs.com/package/jcanvas

**Comment by robertjustjones** [comment]
Nifty! tested and confirmed.

**Pull request merged**
